docs(sphinx): fix build and host on github pages
radiocosmology/driftscan pull request #101
Opened 2021-01-09 05:03 UTC by nritsche

2021-01-11 20:09 UTC, nritsche commented on drift/telescope/disharray.py
```suggestion
# Commented out, because: The class CMUTelescope does not exist. If you know what that's supposed to be, please fix it.
```

2021-01-11 21:15 UTC, jrs65 commented on drift/telescope/disharray.py
Fine for me.

2021-01-11 21:17 UTC, jrs65 approved these changes

2021-01-13 17:01 UTC, jrs65 requested changes

2021-01-13 17:12 UTC, nritsche commented on drift/pipeline/__init__.py
> +driftscan pipeline
This is usually one line (https://numpydoc.readthedocs.io/en/latest/format.html#sections)

2021-01-13 17:12 UTC, nritsche commented
Thanks @jrs65 . There are many more places where these descriptions are missing...

2021-01-13 17:15 UTC, jrs65 commented on drift/pipeline/__init__.py
> +driftscan pipeline
Okay. That's fair. I was looking at how sphinx rendered the html and seeing what would fit. Let me edit them to fit.

2021-01-13 17:18 UTC, jrs65 requested changes

2021-01-13 17:18 UTC, jrs65 commented on drift/util/__init__.py
> +driftscan utils
```suggestion
Utility functions for driftscan.
```

2021-01-13 17:19 UTC, jrs65 requested changes

2021-01-13 17:19 UTC, jrs65 commented on drift/core/__init__.py
> +driftscan core
```suggestion
Core functionality for driftscan modelling.
```

2021-01-13 17:20 UTC, jrs65 commented
@nritsche I've attempted to put a better description in for all the subpackages. I think that's all I have time for now.

2021-01-13 22:47 UTC, jrs65 approved these changes

2021-02-09 23:16 UTC, merged